
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/banner.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct BannerInfoMstData {
	uint32_t	display_order{};
	uint32_t	id{};
	uint32_t	image{};
	std::string	name{};
	std::string	page_type{};
	std::string	param{};
	uint32_t	read_count{};
	std::string	target_os{};
	uint32_t	url{};
};
template <>
struct glz::meta<BannerInfoMstData>
{
    using T = BannerInfoMstData;
    static constexpr auto value = object(
		"XuJL4pc5", &T::display_order,
		"oL71Fz3a", &T::id,
		"1gDkL6XR", &T::image,
		"NyYKc1A5", &T::name,
		"LM34kfVC", &T::page_type,
		"t5R47iwj", &T::param,
		"d36D1g8T", &T::read_count,
		"aL70hVYQ", &T::target_os,
		"jsRoN50z", &T::url
    );
};

struct BannerInfoMst {
    using TYPE = BannerInfoMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<BannerInfoMst>
{
    using T = BannerInfoMst;
    static constexpr auto value = object("Pk5F1vhx", &T::data);
};

