
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/daily_login.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct DailyLoginRewardsUserInfo {
	uint32_t	current_day{};
	uint32_t	id{};
	std::string	message{};
	uint32_t	next_reward_id{};
	uint32_t	remaining_days_till_guaranteed_reward{};
	uint32_t	user_current_count{};
	uint32_t	user_spin_limit_count{};
};
template <>
struct glz::meta<DailyLoginRewardsUserInfo>
{
    using T = DailyLoginRewardsUserInfo;
    static constexpr auto value = object(
		"ad6i23pO", &T::current_day,
		"XIvaD6Jp", &T::id,
		"ZC0msu2L", &T::message,
		"outas79f", &T::next_reward_id,
		"u8iD6ka7", &T::remaining_days_till_guaranteed_reward,
		"35JXN4Ay", &T::user_current_count,
		"5xStG99s", &T::user_spin_limit_count
    );
};




