
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/excludeddungeon.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct ExcludedDungeonMissionMstData {
	uint32_t	id{};
};
template <>
struct glz::meta<ExcludedDungeonMissionMstData>
{
    using T = ExcludedDungeonMissionMstData;
    static constexpr auto value = object(
		"j28VNcUW", &T::id
    );
};

struct ExcludedDungeonMissionMst {
    using TYPE = ExcludedDungeonMissionMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<ExcludedDungeonMissionMst>
{
    using T = ExcludedDungeonMissionMst;
    static constexpr auto value = object("3aDk1xk7", &T::data);
};

