
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/featuring_gate.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct FeatureGatingInfoData {
};
template <>
struct glz::meta<FeatureGatingInfoData>
{
    using T = FeatureGatingInfoData;
    static constexpr auto value = object
    );
};

struct FeatureGatingInfo {
    using TYPE = FeatureGatingInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<FeatureGatingInfo>
{
    using T = FeatureGatingInfo;
    static constexpr auto value = object("2375D38i", &T::data);
};

