
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/firstdesc.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct FirstDescMstData {
};
template <>
struct glz::meta<FirstDescMstData>
{
    using T = FirstDescMstData;
    static constexpr auto value = object
    );
};

struct FirstDescMst {
    using TYPE = FirstDescMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<FirstDescMst>
{
    using T = FirstDescMst;
    static constexpr auto value = object("8UawtzHw", &T::data);
};

