
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/friends.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct FriendPointInfoData {
};
template <>
struct glz::meta<FriendPointInfoData>
{
    using T = FriendPointInfoData;
    static constexpr auto value = object
    );
};

struct FriendPointInfo {
    using TYPE = FriendPointInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<FriendPointInfo>
{
    using T = FriendPointInfo;
    static constexpr auto value = object("6e4b7sQt", &T::data);
};

