
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/gift.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct GiftItemMstData {
};
template <>
struct glz::meta<GiftItemMstData>
{
    using T = GiftItemMstData;
    static constexpr auto value = object
    );
};

struct GiftItemMst {
    using TYPE = GiftItemMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<GiftItemMst>
{
    using T = GiftItemMst;
    static constexpr auto value = object("Bm1WNDQ0", &T::data);
};

