
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/guild.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct GuildInfo {
	uint32_t	id{};
};
template <>
struct glz::meta<GuildInfo>
{
    using T = GuildInfo;
    static constexpr auto value = object(
		"sD73jd20", &T::id
    );
};




