
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/items.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct ItemFavoriteData {
};
template <>
struct glz::meta<ItemFavoriteData>
{
    using T = ItemFavoriteData;
    static constexpr auto value = object
    );
};

struct ItemFavorite {
    using TYPE = ItemFavoriteData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<ItemFavorite>
{
    using T = ItemFavorite;
    static constexpr auto value = object("VSRPkdId", &T::data);
};

