
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/logincampaign.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct UserLoginCampaignInfoData {
	uint32_t	current_day{};
	bool	first_for_the_day{};
	uint32_t	id{};
	uint32_t	total_days{};
};
template <>
struct glz::meta<UserLoginCampaignInfoData>
{
    using T = UserLoginCampaignInfoData;
    static constexpr auto value = object(
		"ad6i23pO", &T::current_day,
		"4tswNoV9", glz::bools_as_numbers<&T::first_for_the_day>,
		"H1Dkq93v", &T::id,
		"1adb38d5", &T::total_days
    );
};

struct UserLoginCampaignInfo {
    using TYPE = UserLoginCampaignInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<UserLoginCampaignInfo>
{
    using T = UserLoginCampaignInfo;
    static constexpr auto value = object("3da6bd0a", &T::data);
};

