
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/missionbreakinfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct MissionBreakInfoData {
};
template <>
struct glz::meta<MissionBreakInfoData>
{
    using T = MissionBreakInfoData;
    static constexpr auto value = object
    );
};

struct MissionBreakInfo {
    using TYPE = MissionBreakInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<MissionBreakInfo>
{
    using T = MissionBreakInfo;
    static constexpr auto value = object("5PR2VmH1", &T::data);
};

