
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/noticeinfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct NoticeInfoData {
	uint32_t	id{};
	std::string	url{};
};
template <>
struct glz::meta<NoticeInfoData>
{
    using T = NoticeInfoData;
    static constexpr auto value = object(
		"xJNom6i0", &T::id,
		"jsRoN50z", &T::url
    );
};

struct NoticeInfo {
    using TYPE = NoticeInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<NoticeInfo>
{
    using T = NoticeInfo;
    static constexpr auto value = object("Pj6zDW3m", &T::data);
};

