
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/npcmessageoverwriteinfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct NpcMessageOverwriteInfoData {
};
template <>
struct glz::meta<NpcMessageOverwriteInfoData>
{
    using T = NpcMessageOverwriteInfoData;
    static constexpr auto value = object
    );
};

struct NpcMessageOverwriteInfo {
    using TYPE = NpcMessageOverwriteInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<NpcMessageOverwriteInfo>
{
    using T = NpcMessageOverwriteInfo;
    static constexpr auto value = object("yNnvj59x", &T::data);
};

