
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/passiveskill.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct ExtraPassiveSkillMstData {
	std::string	description{};
	uint32_t	group_id{};
	uint32_t	id{};
	uint32_t	priority{};
	std::string	process_id{};
	std::string	process_param{};
	uint32_t	rare{};
	std::string	skill_name{};
	std::string	skill_name_s{};
	uint32_t	skill_type{};
	uint32_t	target{};
	std::string	term_param{};
};
template <>
struct glz::meta<ExtraPassiveSkillMstData>
{
    using T = ExtraPassiveSkillMstData;
    static constexpr auto value = object(
		"qp37xTDh", &T::description,
		"outas79f", &T::group_id,
		"cP83zNsv", &T::id,
		"yu18xScw", &T::priority,
		"hjAy9St3", &T::process_id,
		"2Smu5Mtq", &T::process_param,
		"7ofj5xa1", &T::rare,
		"0nxpBDz2", &T::skill_name,
		"UVN5bGoD", &T::skill_name_s,
		"h6UL9A1B", &T::skill_type,
		"moWQ30GH", &T::target,
		"s2gM3deu", &T::term_param
    );
};

struct ExtraPassiveSkillMst {
    using TYPE = ExtraPassiveSkillMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<ExtraPassiveSkillMst>
{
    using T = ExtraPassiveSkillMst;
    static constexpr auto value = object("z5U7utsm", &T::data);
};

