
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/permitplace.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct PermitPlaceData {
};
template <>
struct glz::meta<PermitPlaceData>
{
    using T = PermitPlaceData;
    static constexpr auto value = object
    );
};

struct PermitPlace {
    using TYPE = PermitPlaceData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<PermitPlace>
{
    using T = PermitPlace;
    static constexpr auto value = object("yXNM8kL3", &T::data);
};

struct PermitPlaceMLData {
};
template <>
struct glz::meta<PermitPlaceMLData>
{
    using T = PermitPlaceMLData;
    static constexpr auto value = object
    );
};

struct PermitPlaceML {
    using TYPE = PermitPlaceMLData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<PermitPlaceML>
{
    using T = PermitPlaceML;
    static constexpr auto value = object("Y73mHKS8", &T::data);
};

struct PermitPlaceSPData {
};
template <>
struct glz::meta<PermitPlaceSPData>
{
    using T = PermitPlaceSPData;
    static constexpr auto value = object
    );
};

struct PermitPlaceSP {
    using TYPE = PermitPlaceSPData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<PermitPlaceSP>
{
    using T = PermitPlaceSP;
    static constexpr auto value = object("Y73tHKS8", &T::data);
};

