
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/reinforcementinfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct ReinformenetInfoData {
};
template <>
struct glz::meta<ReinformenetInfoData>
{
    using T = ReinformenetInfoData;
    static constexpr auto value = object
    );
};

struct ReinformenetInfo {
    using TYPE = ReinformenetInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<ReinformenetInfo>
{
    using T = ReinformenetInfo;
    static constexpr auto value = object("xZH6EIQ7", &T::data);
};

