
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/summonticketuserinfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct SummonTicketV2UserInfoData {
};
template <>
struct glz::meta<SummonTicketV2UserInfoData>
{
    using T = SummonTicketV2UserInfoData;
    static constexpr auto value = object
    );
};

struct SummonTicketV2UserInfo {
    using TYPE = SummonTicketV2UserInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<SummonTicketV2UserInfo>
{
    using T = SummonTicketV2UserInfo;
    static constexpr auto value = object("a3d5d12i", &T::data);
};

