
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/net/summonerjournaluserinfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct SummonerJournalUserInfo {
	uint32_t	journal_flag{};
	uint32_t	points{};
	std::string	user_id{};
};
template <>
struct glz::meta<SummonerJournalUserInfo>
{
    using T = SummonerJournalUserInfo;
    static constexpr auto value = object(
		"da365dB8", &T::journal_flag,
		"9hH0neGa", &T::points,
		"h7eY3sAK", &T::user_id
    );
};




