
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/unit.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct UnitExpPatternMstData {
	uint32_t	id{};
	uint32_t	lv{};
	uint32_t	need_exp{};
};
template <>
struct glz::meta<UnitExpPatternMstData>
{
    using T = UnitExpPatternMstData;
    static constexpr auto value = object(
		"5UvTp7q1", &T::id,
		"D9wXQI2V", &T::lv,
		"grKTq15A", &T::need_exp
    );
};

struct UnitExpPatternMst {
    using TYPE = UnitExpPatternMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<UnitExpPatternMst>
{
    using T = UnitExpPatternMst;
    static constexpr auto value = object("JYFGe9y6", &T::data);
};

