
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/userlevel.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct UserLevelMstData {
	uint32_t	action_points{};
	uint32_t	add_friend_count{};
	uint32_t	deck_cost{};
	uint64_t	exp{};
	uint32_t	friend_count{};
	uint32_t	level{};
};
template <>
struct glz::meta<UserLevelMstData>
{
    using T = UserLevelMstData;
    static constexpr auto value = object(
		"0P9X1YHs", &T::action_points,
		"GZ2rKW90", &T::add_friend_count,
		"ziex06DY", &T::deck_cost,
		"d96tuT2E", &T::exp,
		"oFQ3mbS6", &T::friend_count,
		"D9wXQI2V", &T::level
    );
};

struct UserLevelMst {
    using TYPE = UserLevelMstData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<UserLevelMst>
{
    using T = UserLevelMst;
    static constexpr auto value = object("YDv9bJ3s", &T::data);
};

