
/*
    This file was autogenerated by decompfrontier packet-generator.
    Generation date: 2025-04-10 17:17:19

    DO NOT MODIFY THIS FILE! MODIFY THE FILE ./data/mst/versioninfo.py INSIDE THE
    PACKET GENERATOR REPOSITORY AND RUN THE GENERATION AGAIN!
*/
#pragma once

#include <glaze_helpers.hpp> // c++ runtime helpers

struct VersionInfoData {
	std::string	description{};
	uint32_t	id{};
	uint32_t	subversion{};
	uint32_t	unknown{};
	uint32_t	version{};
};
template <>
struct glz::meta<VersionInfoData>
{
    using T = VersionInfoData;
    static constexpr auto value = object(
		"e3QNsuZ8", &T::description,
		"moWQ30GH", &T::id,
		"5kbnkTp0", &T::subversion,
		"H6k1LIxC", &T::unknown,
		"d2RFtP8T", &T::version
    );
};

struct VersionInfo {
    using TYPE = VersionInfoData;
    std::deque<TYPE> data;
};
template <>
struct glz::meta<VersionInfo>
{
    using T = VersionInfo;
    static constexpr auto value = object("KeC10fuL", &T::data);
};

